version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=simplebank
    ports:
      - '5432:5432'
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgres://postgres:mysecretpassword@postgres:5432/simplebank?sslmode=disable
    entrypoint: ['/app/wait-for.sh', 'postgres:5432', '--', '/app/start.sh']
    command: ['/app/main']
