name: Run all unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: simplebank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Check Go version
        run: go version

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install go-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrate_up

      - name: Create .env file
        run: |
          touch config.env
          echo DB_SOURCE="postgres://postgres:mysecretpassword@localhost:5432/simplebank?sslmode=disable" >> config.env
          echo DB_DRIVER=${{ secrets.DB_DRIVER }} >> config.env
          echo TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }} >> config.env
          echo ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION }} >> config.env
          echo SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }} >> config.env

      - name: Run tests
        run: make test